/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.muenchen.jfs17;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7176668030737939696L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"de.muenchen.jfs17\",\"fields\":[{\"name\":\"item\",\"type\":{\"type\":\"record\",\"name\":\"LineItem\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"default\":\"coffee\"},{\"name\":\"quantity\",\"type\":\"int\",\"default\":\"1\"},{\"name\":\"milk\",\"type\":\"boolean\",\"default\":\"false\"},{\"name\":\"size\",\"type\":{\"type\":\"enum\",\"name\":\"Sizes\",\"symbols\":[\"LARGE\",\"MIDDLE\",\"SMALL\"]},\"default\":\"MIDDLE\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<Order>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Order to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Order from a ByteBuffer. */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public de.muenchen.jfs17.LineItem item;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param item The new value for item
   */
  public Order(de.muenchen.jfs17.LineItem item) {
    this.item = item;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return item;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: item = (de.muenchen.jfs17.LineItem)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'item' field.
   * @return The value of the 'item' field.
   */
  public de.muenchen.jfs17.LineItem getItem() {
    return item;
  }

  /**
   * Sets the value of the 'item' field.
   * @param value the value to set.
   */
  public void setItem(de.muenchen.jfs17.LineItem value) {
    this.item = value;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static de.muenchen.jfs17.Order.Builder newBuilder() {
    return new de.muenchen.jfs17.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static de.muenchen.jfs17.Order.Builder newBuilder(de.muenchen.jfs17.Order.Builder other) {
    return new de.muenchen.jfs17.Order.Builder(other);
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static de.muenchen.jfs17.Order.Builder newBuilder(de.muenchen.jfs17.Order other) {
    return new de.muenchen.jfs17.Order.Builder(other);
  }

  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private de.muenchen.jfs17.LineItem item;
    private de.muenchen.jfs17.LineItem.Builder itemBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.muenchen.jfs17.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.item)) {
        this.item = data().deepCopy(fields()[0].schema(), other.item);
        fieldSetFlags()[0] = true;
      }
      if (other.hasItemBuilder()) {
        this.itemBuilder = de.muenchen.jfs17.LineItem.newBuilder(other.getItemBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(de.muenchen.jfs17.Order other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.item)) {
        this.item = data().deepCopy(fields()[0].schema(), other.item);
        fieldSetFlags()[0] = true;
      }
      this.itemBuilder = null;
    }

    /**
      * Gets the value of the 'item' field.
      * @return The value.
      */
    public de.muenchen.jfs17.LineItem getItem() {
      return item;
    }

    /**
      * Sets the value of the 'item' field.
      * @param value The value of 'item'.
      * @return This builder.
      */
    public de.muenchen.jfs17.Order.Builder setItem(de.muenchen.jfs17.LineItem value) {
      validate(fields()[0], value);
      this.itemBuilder = null;
      this.item = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'item' field has been set.
      * @return True if the 'item' field has been set, false otherwise.
      */
    public boolean hasItem() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'item' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public de.muenchen.jfs17.LineItem.Builder getItemBuilder() {
      if (itemBuilder == null) {
        if (hasItem()) {
          setItemBuilder(de.muenchen.jfs17.LineItem.newBuilder(item));
        } else {
          setItemBuilder(de.muenchen.jfs17.LineItem.newBuilder());
        }
      }
      return itemBuilder;
    }

    /**
     * Sets the Builder instance for the 'item' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public de.muenchen.jfs17.Order.Builder setItemBuilder(de.muenchen.jfs17.LineItem.Builder value) {
      clearItem();
      itemBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'item' field has an active Builder instance
     * @return True if the 'item' field has an active Builder instance
     */
    public boolean hasItemBuilder() {
      return itemBuilder != null;
    }

    /**
      * Clears the value of the 'item' field.
      * @return This builder.
      */
    public de.muenchen.jfs17.Order.Builder clearItem() {
      item = null;
      itemBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        if (itemBuilder != null) {
          record.item = this.itemBuilder.build();
        } else {
          record.item = fieldSetFlags()[0] ? this.item : (de.muenchen.jfs17.LineItem) defaultValue(fields()[0]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
