/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.muenchen.jfs17;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RechnungsPosten extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4359776463254188169L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RechnungsPosten\",\"namespace\":\"de.muenchen.jfs17\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"default\":\"coffee\"},{\"name\":\"quantity\",\"type\":\"int\",\"default\":\"1\"},{\"name\":\"milk\",\"type\":\"boolean\",\"default\":\"false\"},{\"name\":\"size\",\"type\":{\"type\":\"enum\",\"name\":\"Sizes\",\"symbols\":[\"LARGE\",\"MIDDLE\",\"SMALL\"]},\"default\":\"MIDDLE\"}],\"aliases\":[\"LineItem\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RechnungsPosten> ENCODER =
      new BinaryMessageEncoder<RechnungsPosten>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RechnungsPosten> DECODER =
      new BinaryMessageDecoder<RechnungsPosten>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RechnungsPosten> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RechnungsPosten> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RechnungsPosten>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RechnungsPosten to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RechnungsPosten from a ByteBuffer. */
  public static RechnungsPosten fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int quantity;
  @Deprecated public boolean milk;
  @Deprecated public de.muenchen.jfs17.Sizes size;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RechnungsPosten() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param quantity The new value for quantity
   * @param milk The new value for milk
   * @param size The new value for size
   */
  public RechnungsPosten(java.lang.CharSequence name, java.lang.Integer quantity, java.lang.Boolean milk, de.muenchen.jfs17.Sizes size) {
    this.name = name;
    this.quantity = quantity;
    this.milk = milk;
    this.size = size;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return quantity;
    case 2: return milk;
    case 3: return size;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: quantity = (java.lang.Integer)value$; break;
    case 2: milk = (java.lang.Boolean)value$; break;
    case 3: size = (de.muenchen.jfs17.Sizes)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public java.lang.Integer getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Integer value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'milk' field.
   * @return The value of the 'milk' field.
   */
  public java.lang.Boolean getMilk() {
    return milk;
  }

  /**
   * Sets the value of the 'milk' field.
   * @param value the value to set.
   */
  public void setMilk(java.lang.Boolean value) {
    this.milk = value;
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public de.muenchen.jfs17.Sizes getSize() {
    return size;
  }

  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(de.muenchen.jfs17.Sizes value) {
    this.size = value;
  }

  /**
   * Creates a new RechnungsPosten RecordBuilder.
   * @return A new RechnungsPosten RecordBuilder
   */
  public static de.muenchen.jfs17.RechnungsPosten.Builder newBuilder() {
    return new de.muenchen.jfs17.RechnungsPosten.Builder();
  }

  /**
   * Creates a new RechnungsPosten RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RechnungsPosten RecordBuilder
   */
  public static de.muenchen.jfs17.RechnungsPosten.Builder newBuilder(de.muenchen.jfs17.RechnungsPosten.Builder other) {
    return new de.muenchen.jfs17.RechnungsPosten.Builder(other);
  }

  /**
   * Creates a new RechnungsPosten RecordBuilder by copying an existing RechnungsPosten instance.
   * @param other The existing instance to copy.
   * @return A new RechnungsPosten RecordBuilder
   */
  public static de.muenchen.jfs17.RechnungsPosten.Builder newBuilder(de.muenchen.jfs17.RechnungsPosten other) {
    return new de.muenchen.jfs17.RechnungsPosten.Builder(other);
  }

  /**
   * RecordBuilder for RechnungsPosten instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RechnungsPosten>
    implements org.apache.avro.data.RecordBuilder<RechnungsPosten> {

    private java.lang.CharSequence name;
    private int quantity;
    private boolean milk;
    private de.muenchen.jfs17.Sizes size;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.muenchen.jfs17.RechnungsPosten.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.milk)) {
        this.milk = data().deepCopy(fields()[2].schema(), other.milk);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.size)) {
        this.size = data().deepCopy(fields()[3].schema(), other.size);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RechnungsPosten instance
     * @param other The existing instance to copy.
     */
    private Builder(de.muenchen.jfs17.RechnungsPosten other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.milk)) {
        this.milk = data().deepCopy(fields()[2].schema(), other.milk);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.size)) {
        this.size = data().deepCopy(fields()[3].schema(), other.size);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public java.lang.Integer getQuantity() {
      return quantity;
    }

    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder setQuantity(int value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'milk' field.
      * @return The value.
      */
    public java.lang.Boolean getMilk() {
      return milk;
    }

    /**
      * Sets the value of the 'milk' field.
      * @param value The value of 'milk'.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder setMilk(boolean value) {
      validate(fields()[2], value);
      this.milk = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'milk' field has been set.
      * @return True if the 'milk' field has been set, false otherwise.
      */
    public boolean hasMilk() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'milk' field.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder clearMilk() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public de.muenchen.jfs17.Sizes getSize() {
      return size;
    }

    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder setSize(de.muenchen.jfs17.Sizes value) {
      validate(fields()[3], value);
      this.size = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public de.muenchen.jfs17.RechnungsPosten.Builder clearSize() {
      size = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RechnungsPosten build() {
      try {
        RechnungsPosten record = new RechnungsPosten();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Integer) defaultValue(fields()[1]);
        record.milk = fieldSetFlags()[2] ? this.milk : (java.lang.Boolean) defaultValue(fields()[2]);
        record.size = fieldSetFlags()[3] ? this.size : (de.muenchen.jfs17.Sizes) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RechnungsPosten>
    WRITER$ = (org.apache.avro.io.DatumWriter<RechnungsPosten>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RechnungsPosten>
    READER$ = (org.apache.avro.io.DatumReader<RechnungsPosten>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
