/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.muenchen.jfs17;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Sizes {
  LARGE, MIDDLE, SMALL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Sizes\",\"namespace\":\"de.muenchen.jfs17\",\"symbols\":[\"LARGE\",\"MIDDLE\",\"SMALL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
